name: gradients
description: >-
  Implementations of Flutter's linear, radial, and sweep gradients
  with support for the CMYK, HSI, HSL, HSP, HSB, LAB, Oklab, RGB,
  and XYZ color spaces.
version: 0.1.1+2
homepage: https://github.com/james-alex/gradients

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=3.27.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_color_models: ^1.3.2
  powers: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
